import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.recipes': 'Recipes',
    'nav.benefits': 'Benefits',
    'nav.faq': 'FAQ',
    'hero.title': 'Discover the Power of the Ocean',
    'hero.subtitle': 'Premium organic sea vegetables for your health and culinary adventures',
    'hero.cta': 'Shop Now',
    'hero.learnMore': 'Learn More',
    'problem.title': 'Why Sea Vegetables?',
    'problem.subtitle': 'Nature\'s Most Nutrient-Dense Superfood',
    'problem.point1': 'Rich in Essential Minerals',
    'problem.point1.desc': '11x more calcium than milk, plus iodine, iron, and magnesium',
    'problem.point2': 'Natural Detoxifier',
    'problem.point2.desc': 'Helps remove heavy metals and supports liver function',
    'problem.point3': 'Umami Flavor Boost',
    'problem.point3.desc': 'Add depth and complexity to any dish naturally',
    'products.title': 'Our Sea Vegetable Collection',
    'products.subtitle': 'Sustainably harvested, organic certified, and packed with nutrients',
    'products.addToCart': 'Add to Cart',
    'products.learnMore': 'Learn More',
    'benefits.title': 'Health Benefits of Sea Vegetables',
    'benefits.subtitle': 'Backed by science, trusted by chefs',
    'benefit.thyroid': 'Thyroid Support',
    'benefit.thyroid.desc': 'Rich in iodine for healthy thyroid function',
    'benefit.bones': 'Strong Bones',
    'benefit.bones.desc': 'Exceptional calcium and vitamin K content',
    'benefit.immunity': 'Immune Boost',
    'benefit.immunity.desc': 'High in antioxidants and vitamin C',
    'benefit.digestion': 'Gut Health',
    'benefit.digestion.desc': 'Prebiotic fiber supports digestive wellness',
    'recipes.title': 'Delicious Sea Vegetable Recipes',
    'recipes.subtitle': 'From traditional to modern cuisine',
    'recipes.viewRecipe': 'View Recipe',
    'howItWorks.title': 'How It Works',
    'howItWorks.step1': 'Choose Your Products',
    'howItWorks.step1.desc': 'Browse our organic sea vegetable collection',
    'howItWorks.step2': 'Get Recipe Ideas',
    'howItWorks.step2.desc': 'Chat with Algae for personalized suggestions',
    'howItWorks.step3': 'Enjoy & Thrive',
    'howItWorks.step3.desc': 'Experience better health and amazing flavors',
    'testimonials.title': 'What Our Customers Say',
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'What are sea vegetables?',
    'faq.a1': 'Sea vegetables are edible seaweed and algae varieties rich in minerals, vitamins, and unique compounds.',
    'faq.q2': 'How do I use them?',
    'faq.a2': 'Add to soups, salads, rice dishes, or use as a seasoning. Our chat agent can suggest recipes!',
    'faq.q3': 'Are they safe?',
    'faq.a3': 'Yes! Our products are tested for heavy metals and sustainably harvested from clean waters.',
    'faq.q4': 'How should I store them?',
    'faq.a4': 'Keep in a cool, dry place away from direct sunlight. They have a long shelf life.',
    'footer.about': 'About Algamar',
    'footer.aboutText': 'Bringing the ocean\'s bounty to your table since 1996',
    'footer.contact': 'Contact',
    'footer.email': 'Email',
    'footer.phone': 'Phone',
    'footer.follow': 'Follow Us',
    'footer.rights': 'All rights reserved',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.checkout': 'Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'chat.placeholder': 'Ask Algae anything...',
    'chat.title': 'Chat with Algae',
    'chat.subtitle': 'Your ocean wellness guide',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.recipes': 'Recettes',
    'nav.benefits': 'Bienfaits',
    'nav.faq': 'FAQ',
    'hero.title': 'Découvrez le Pouvoir de l\'Océan',
    'hero.subtitle': 'Légumes de mer biologiques premium pour votre santé et vos aventures culinaires',
    'hero.cta': 'Acheter',
    'hero.learnMore': 'En Savoir Plus',
    'problem.title': 'Pourquoi les Légumes de Mer?',
    'problem.subtitle': 'Le Superaliment le Plus Nutritif de la Nature',
    'problem.point1': 'Riche en Minéraux Essentiels',
    'problem.point1.desc': '11x plus de calcium que le lait, plus iode, fer et magnésium',
    'problem.point2': 'Détoxifiant Naturel',
    'problem.point2.desc': 'Aide à éliminer les métaux lourds et soutient la fonction hépatique',
    'problem.point3': 'Boost de Saveur Umami',
    'problem.point3.desc': 'Ajoute profondeur et complexité à tout plat naturellement',
    'products.title': 'Notre Collection de Légumes de Mer',
    'products.subtitle': 'Récoltés durablement, certifiés bio, et riches en nutriments',
    'products.addToCart': 'Ajouter au Panier',
    'products.learnMore': 'En Savoir Plus',
    'benefits.title': 'Bienfaits des Légumes de Mer',
    'benefits.subtitle': 'Soutenu par la science, approuvé par les chefs',
    'benefit.thyroid': 'Soutien Thyroïdien',
    'benefit.thyroid.desc': 'Riche en iode pour une fonction thyroïdienne saine',
    'benefit.bones': 'Os Solides',
    'benefit.bones.desc': 'Teneur exceptionnelle en calcium et vitamine K',
    'benefit.immunity': 'Boost Immunitaire',
    'benefit.immunity.desc': 'Riche en antioxydants et vitamine C',
    'benefit.digestion': 'Santé Intestinale',
    'benefit.digestion.desc': 'Les fibres prébiotiques soutiennent le bien-être digestif',
    'recipes.title': 'Délicieuses Recettes aux Légumes de Mer',
    'recipes.subtitle': 'De la cuisine traditionnelle à moderne',
    'recipes.viewRecipe': 'Voir la Recette',
    'howItWorks.title': 'Comment Ça Marche',
    'howItWorks.step1': 'Choisissez Vos Produits',
    'howItWorks.step1.desc': 'Parcourez notre collection de légumes de mer bio',
    'howItWorks.step2': 'Obtenez des Idées de Recettes',
    'howItWorks.step2.desc': 'Discutez avec Algae pour des suggestions personnalisées',
    'howItWorks.step3': 'Savourez & Prospérez',
    'howItWorks.step3.desc': 'Découvrez une meilleure santé et des saveurs incroyables',
    'testimonials.title': 'Ce Que Disent Nos Clients',
    'faq.title': 'Questions Fréquentes',
    'faq.q1': 'Que sont les légumes de mer?',
    'faq.a1': 'Les légumes de mer sont des variétés d\'algues comestibles riches en minéraux, vitamines et composés uniques.',
    'faq.q2': 'Comment les utiliser?',
    'faq.a2': 'Ajoutez-les aux soupes, salades, plats de riz ou utilisez comme assaisonnement. Notre agent peut suggérer des recettes!',
    'faq.q3': 'Sont-ils sûrs?',
    'faq.a3': 'Oui! Nos produits sont testés pour les métaux lourds et récoltés durablement dans des eaux propres.',
    'faq.q4': 'Comment les conserver?',
    'faq.a4': 'Conservez dans un endroit frais et sec à l\'abri de la lumière directe. Ils ont une longue durée de conservation.',
    'footer.about': 'À Propos d\'Algamar',
    'footer.aboutText': 'Apporter les richesses de l\'océan à votre table depuis 1996',
    'footer.contact': 'Contact',
    'footer.email': 'Email',
    'footer.phone': 'Téléphone',
    'footer.follow': 'Suivez-Nous',
    'footer.rights': 'Tous droits réservés',
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.subtotal': 'Sous-total',
    'cart.checkout': 'Passer Commande',
    'cart.continueShopping': 'Continuer les Achats',
    'chat.placeholder': 'Demandez à Algae...',
    'chat.title': 'Discuter avec Algae',
    'chat.subtitle': 'Votre guide du bien-être océanique',
  },
  nl: {
    'nav.home': 'Home',
    'nav.products': 'Producten',
    'nav.recipes': 'Recepten',
    'nav.benefits': 'Voordelen',
    'nav.faq': 'FAQ',
    'hero.title': 'Ontdek de Kracht van de Oceaan',
    'hero.subtitle': 'Premium biologische zeegroenten voor uw gezondheid en culinaire avonturen',
    'hero.cta': 'Nu Kopen',
    'hero.learnMore': 'Meer Info',
    'problem.title': 'Waarom Zeegroenten?',
    'problem.subtitle': 'Het Meest Voedingsrijke Superfood van de Natuur',
    'problem.point1': 'Rijk aan Essentiële Mineralen',
    'problem.point1.desc': '11x meer calcium dan melk, plus jodium, ijzer en magnesium',
    'problem.point2': 'Natuurlijke Detoxifier',
    'problem.point2.desc': 'Helpt zware metalen te verwijderen en ondersteunt leverfunctie',
    'problem.point3': 'Umami Smaak Boost',
    'problem.point3.desc': 'Voeg diepte en complexiteit toe aan elk gerecht op natuurlijke wijze',
    'products.title': 'Onze Zeegroenten Collectie',
    'products.subtitle': 'Duurzaam geoogst, biologisch gecertificeerd en vol voedingsstoffen',
    'products.addToCart': 'Toevoegen aan Winkelwagen',
    'products.learnMore': 'Meer Info',
    'benefits.title': 'Gezondheidsvoordelen van Zeegroenten',
    'benefits.subtitle': 'Ondersteund door wetenschap, vertrouwd door chefs',
    'benefit.thyroid': 'Schildklier Ondersteuning',
    'benefit.thyroid.desc': 'Rijk aan jodium voor gezonde schildklierfunctie',
    'benefit.bones': 'Sterke Botten',
    'benefit.bones.desc': 'Uitzonderlijk calcium en vitamine K gehalte',
    'benefit.immunity': 'Immuun Boost',
    'benefit.immunity.desc': 'Hoog in antioxidanten en vitamine C',
    'benefit.digestion': 'Darmgezondheid',
    'benefit.digestion.desc': 'Prebiotische vezels ondersteunen spijsvertering',
    'recipes.title': 'Heerlijke Zeegroenten Recepten',
    'recipes.subtitle': 'Van traditioneel tot moderne keuken',
    'recipes.viewRecipe': 'Bekijk Recept',
    'howItWorks.title': 'Hoe Het Werkt',
    'howItWorks.step1': 'Kies Uw Producten',
    'howItWorks.step1.desc': 'Blader door onze biologische zeegroenten collectie',
    'howItWorks.step2': 'Krijg Recept Ideeën',
    'howItWorks.step2.desc': 'Chat met Algae voor gepersonaliseerde suggesties',
    'howItWorks.step3': 'Geniet & Bloei',
    'howItWorks.step3.desc': 'Ervaar betere gezondheid en geweldige smaken',
    'testimonials.title': 'Wat Onze Klanten Zeggen',
    'faq.title': 'Veelgestelde Vragen',
    'faq.q1': 'Wat zijn zeegroenten?',
    'faq.a1': 'Zeegroenten zijn eetbare zeewier en algen variëteiten rijk aan mineralen, vitamines en unieke verbindingen.',
    'faq.q2': 'Hoe gebruik ik ze?',
    'faq.a2': 'Voeg toe aan soepen, salades, rijstgerechten of gebruik als kruiding. Onze chat agent kan recepten voorstellen!',
    'faq.q3': 'Zijn ze veilig?',
    'faq.a3': 'Ja! Onze producten worden getest op zware metalen en duurzaam geoogst uit schoon water.',
    'faq.q4': 'Hoe moet ik ze bewaren?',
    'faq.a4': 'Bewaar op een koele, droge plaats uit direct zonlicht. Ze hebben een lange houdbaarheid.',
    'footer.about': 'Over Algamar',
    'footer.aboutText': 'De rijkdom van de oceaan naar uw tafel brengen sinds 1996',
    'footer.contact': 'Contact',
    'footer.email': 'Email',
    'footer.phone': 'Telefoon',
    'footer.follow': 'Volg Ons',
    'footer.rights': 'Alle rechten voorbehouden',
    'cart.title': 'Winkelwagen',
    'cart.empty': 'Uw winkelwagen is leeg',
    'cart.subtotal': 'Subtotaal',
    'cart.checkout': 'Afrekenen',
    'cart.continueShopping': 'Verder Winkelen',
    'chat.placeholder': 'Vraag Algae iets...',
    'chat.title': 'Chat met Algae',
    'chat.subtitle': 'Uw oceaan wellness gids',
  },
};
